swagger: "2.0"
info:
  description: "This is the API documentation of NIFTTT [GitHub Repo](https://github.com/ArberRrapaj/NIFTTT)."
  version: "1.0.0"
  title: "NIFTTT API Documentation"
host: "localhost"
tags:
- name: "user"
  description: "User related paths"
- name: "rule"
  description: "Access to Petstore orders"
schemes:
- "https"
- "http"
paths:
  /users/{id}:
    get:
      tags:
      - "user"
      summary: "Get user by ID"
      operationId: "getUserById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/User"
    put:
      tags:
      - "user"
      summary: "Update a user"
      operationId: "updateUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        description: "User Object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "success"
    delete:
      tags:
      - "user"
      summary: "Delete a user"
      operationId: "deleteUser"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
      responses:
        200:
          description: "success"
  /users:
    post:
      tags:
      - "user"
      summary: "Add a user (registration)"
      operationId: "postUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "user-data"
        description: "User Object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "success"
  /rules/{id}:
    get:
      tags:
      - "rule"
      summary: "Get rule by ID"
      operationId: "getRuleById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/Rule"
    put:
      tags:
      - "rule"
      summary: "Update a rule"
      operationId: "updateRule"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        description: "Rule Object"
        required: true
        schema:
          $ref: "#/definitions/Rule"
      responses:
        200:
          description: "success"
    delete:
      tags:
      - "rule"
      summary: "Delete a rule"
      operationId: "deleteRule"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
      responses:
        200:
          description: "success"
  /rules:
    post:
      tags:
      - "rule"
      summary: "Add a rule (registration)"
      operationId: "postRule"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "rule-data"
        description: "Rule Object"
        required: true
        schema:
          $ref: "#/definitions/Rule"
      responses:
        200:
          description: "success"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
  Rule:
    type: "object"
    properties:
      id:
        type: "integer"
      label:
        type: "string"
      automationsTotal:
        type: "integer"
      automationsMonth:
        type: "integer"
      trigger-id:
        type: "string"
      action-id:
        type: "string"
      trigger-payload:
        type: "object"
      action-payload:
        type: "object"
